apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: websites.smartx.com
spec:
  group: smartx.com
  version: v1
  names:
    kind: Website
    plural: websites
  scope: Namespaced
